name: "Build simple Docker image"
description: "Login, setup buildx, and build/push a single Dockerfile"
inputs:
    dockerfile:
        description: "Path to Dockerfile"
        required: true
    tags:
        description: "Tags to apply (one per line)"
        required: true
    build-args:
        description: "Build arguments (one per line)"
        required: false
    no_cache:
        description: "Use --no-cache"
        required: false
        default: "false"
runs:
    using: "composite"
    steps:
        -   name: Setup Buildx
            uses: docker/setup-buildx-action@v3
            with:
                driver-opts: image=moby/buildkit:master-rootless

        -   name: Build & push
            uses: docker/build-push-action@v6
            with:
                context: .
                file: ${{ inputs.dockerfile }}
                push: true
                provenance: true
                sbom: true
                no-cache: ${{ inputs.no_cache == 'true' }}
                tags: ${{ inputs.tags }}
                build-args: ${{ inputs.build-args }}
