#!/bin/sh
set -e

dir=/usr/src/php

usage() {
    echo "usage: $0 COMMAND"
    echo
    echo "Manage php source tarball lifecycle."
    echo
    echo "Commands:"
    echo "   extract  extract php source tarball into directory $dir if not already done."
    echo "   delete   delete extracted php source located into $dir if not already done."
    echo
}

case "$1" in
    extract)
        echo "extract"
        ;;

    delete)
        echo "delete"
        ;;

    *)
        usage
        exit 1
        ;;
esac
