name: "Build PHP-FPM base"
description: "Clone php-src then build base image"
inputs:
    dockerfile:
        description: "Path to Dockerfile"
        required: true
    tags:
        description: "Tags to apply (one per line)"
        required: true
    no_cache:
        description: "Use --no-cache"
        required: false
        default: "false"
    php_branch:
        description: "PHP branch to clone (empty = default branch)"
        required: false
        default: ""
    php_version:
        description: "PHP version for build"
        required: false
        default: "8.5.0-dev"
runs:
    using: "composite"
    steps:
        -   uses: actions/checkout@v6

        -   name: Clone php-src
            shell: bash
            run: |
                set -euo pipefail
                mkdir -p php
                cd php
                CLONE_CMD="git clone --single-branch"
                if [ -n "${{ inputs.php_branch }}" ]; then
                    CLONE_CMD="$CLONE_CMD --branch ${{ inputs.php_branch }}"
                fi
                CLONE_CMD="$CLONE_CMD https://github.com/fork-php/php-src.git source"
                eval $CLONE_CMD
                cd source && git submodule update --init --force
                docker pull ghcr.io/valksor/curl:latest

        -   uses: ./.github/actions/build-simple
            with:
                dockerfile: ${{ inputs.dockerfile }}
                tags: ${{ inputs.tags }}
                no_cache: ${{ inputs.no_cache }}
                build-args: |
                    PHP_VERSION=${{ inputs.php_version }}
                    BASE_TAG=${{ inputs.php_branch == 'master' && ':master' || ':latest' }}
