name: "Build PHP-FPM sockets"
description: "Build socket and testing-socket images"
inputs:
    dockerfile1:
        description: "First Dockerfile"
        required: true
    tags1:
        description: "First image tags"
        required: true
    dockerfile2:
        description: "Second Dockerfile"
        required: true
    tags2:
        description: "Second image tags"
        required: true
    no_cache:
        description: "Use --no-cache"
        required: false
        default: "false"
    base_tag:
        description: "Base image tag suffix"
        required: false
        default: ""
runs:
    using: "composite"
    steps:
        -   name: Pull base images
            shell: bash
            run: |
                set -euo pipefail
                BASE_TAG=":latest"
                if [ "${{ inputs.base_tag }}" = "-master" ]; then
                    BASE_TAG=":master"
                fi
                docker pull ghcr.io/valksor/php/fpm${BASE_TAG}
                docker pull ghcr.io/valksor/php/fpm-testing${BASE_TAG}
        -   uses: ./.github/actions/build-simple
            with:
                dockerfile: ${{ inputs.dockerfile1 }}
                tags: ${{ inputs.tags1 }}
                no_cache: ${{ inputs.no_cache }}
                build-args: |
                    BASE_TAG=${{ inputs.base_tag }}
        -   uses: ./.github/actions/build-simple
            with:
                dockerfile: ${{ inputs.dockerfile2 }}
                tags: ${{ inputs.tags2 }}
                no_cache: ${{ inputs.no_cache }}
                build-args: |
                    BASE_TAG=${{ inputs.base_tag}}
